scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'Microservice tracker application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['tracker:8080']
        labels:
          application: 'Microservice tracker application'